---
title: "Model Report"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

<style>
body{
    font-size: 14pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    cache = FALSE,
    warning = FALSE,
    message = FALSE,
    fig.align = "center"
)

library(tidyverse)
library(here)
library(glue)
library(rstan)
library(bayesplot)
library(patchwork)
source(here("analysis/utils.R"))

bayesplot::color_scheme_set("red")

```

```{r}
## Defaults --------------------------------------------------------------#

if (!exists("params")) {
  params <- list(
    model_fname = "model/ppool_combined.RData",
    data_fname = "data/model-data_s'18'19'20'21_combined_2022-03-10.rds"
  )
}



```


```{r}

## Pull in model --------------------------------------------------------------#
ext <- tools::file_ext(params[["model_fname"]])
if (ext == "RData") {
  load(file = here(params[["model_fname"]])) # `pm_fit`  
} else if (ext == "rds") {
  pm_fit <- readRDS(here(params[["model_fname"]]))
}


#params$data_fname <- "data/model-data_s'18'19'20'21_combined_2022-03-24.rds"
model_data <- readRDS(here(params[["data_fname"]]))

team_names <- colnames(model_data)[2:32]
player_names <- colnames(model_data)[33:ncol(model_data)]

model <- pull_modname(params[["model_fname"]])
```

## Model info

- Data: "`r basename(params[["data_fname"]])`"
- Model: "`r basename(params[["model_fname"]])`"

```{r}
teams_included = !grepl("nt",model)
off_def = grepl("off-def",model)
```


## Parameter Estimates 

```{r, eval = teams_included}
# All teams 
plot_post_parameter(pm_fit, vars(starts_with("alfa")), team_names) +
  labs(title = "Team Effects")
# mcmc_intervals(pm_fit, vars(starts_with("alfa")))
```


```{r, eval = off_def}

###### Offensive Effects ##########
# All players.  Note the updated aesthetic allows this to be readable, even if
# we can't pull out individual players
np = length(player_names)/2
plot_post_parameter(pm_fit, vars(starts_with("beta_off")), player_names[1:np]) +
  theme(axis.text.y = element_blank()) +
  labs(title = "Offensive Player Effects")

# top 30 players; bottom 30 players 
top_n <- 30
bottom_n <- 30
plot_post_parameter(pm_fit, vars(starts_with("beta_off")), player_names[1:np], top = top_n) +
  labs(title = glue("Top {top_n} Offensive Player Effects"))
plot_post_parameter(pm_fit, vars(starts_with("beta_off")), player_names[1:np], top = -bottom_n) +
  labs(title = glue("Bottom {bottom_n} Offensive Player Effects"))


######### Defensive Effects ################
# All players.  Note the updated aesthetic allows this to be readable, even if
# we can't pull out individual players
np = length(player_names)/2
plot_post_parameter(pm_fit, vars(starts_with("beta_def")), player_names[1:np]) +
  theme(axis.text.y = element_blank()) +
  labs(title = "Defensive Player Effects")

# top 30 players; bottom 30 players 
top_n <- 30
bottom_n <- 30
plot_post_parameter(pm_fit, vars(starts_with("beta_def")), player_names[1:np], top = top_n) +
  labs(title = glue("Top {top_n} Defensive Player Effects"))
plot_post_parameter(pm_fit, vars(starts_with("beta_def")), player_names[1:np], top = -bottom_n) +
  labs(title = glue("Bottom {bottom_n} Defensive Player Effects"))




```




```{r, eval = !off_def}
######## Overall effects ############

# All players.  Note the updated aesthetic allows this to be readable, even if
# we can't pull out individual players
plot_post_parameter(pm_fit, vars(starts_with("beta")), player_names) +
  theme(axis.text.y = element_blank()) +
  labs(title = "Overall Player Effects")

# top 30 players; bottom 30 players 
top_n <- 30
bottom_n <- 30
plot_post_parameter(pm_fit, vars(starts_with("beta")), player_names, top = top_n) +
  labs(title = glue("Top {top_n} Player Effects"))
plot_post_parameter(pm_fit, vars(starts_with("beta")), player_names, top = -bottom_n) +
  labs(title = glue("Bottom {bottom_n} Player Effects"))
```


```{r}
# The bayesplot default is fine for now.  See https://mc-stan.org/bayesplot/.
bayesplot::mcmc_hist(pm_fit, pars = "lambda") +
  labs(title = "Lambda across MCMC iterations")

```

## Diagnostics

```{r}
## Diagnostics ----------------------------------------------------------------#

mcmc_trace(pm_fit, pars = "lambda") +
  labs(x = "Iteration", title = "MCMC chain plot for Lambda")

if (teams_included & off_def) {
  par_list <- c("lambda", "alfa", "beta_off", "beta_def")
} else if (off_def) {
  par_list <- c("lambda", "beta_off", "beta_def")
} else {
  par_list <- c("lambda", "alfa", "beta")
}
  
plot_rhat_multi(pm_fit, par_list) +
  patchwork::plot_annotation(title = "Rhat plot")


plot_neff_multi(pm_fit, par_list) +
  patchwork::plot_annotation(title = "Effective sample size plot")
```


### Sample Auto Correlation Plots

```{r}
mcmc_acf(pm_fit, pars = "lambda", lags = 100)

if (teams_included && off_def) {
  mcmc_acf(pm_fit, pars = "alfa[1]", lags = 100)
  mcmc_acf(pm_fit, pars = "beta_off[1]", lags = 100)
  mcmc_acf(pm_fit, pars = "beta_def[1]", lags = 100)
} else if (off_def) {
  mcmc_acf(pm_fit, pars = "beta_off[1]", lags = 100)
  mcmc_acf(pm_fit, pars = "beta_def[1]", lags = 100)
} else {
  mcmc_acf(pm_fit, pars = "alfa[1]", lags = 100)
  mcmc_acf(pm_fit, pars = "beta[1]", lags = 100)
}


```

