install.packages("tidyverse")
install.packages("devtools")
install.packages("here")
install.packages("glue")
install.packages("Matrix")
install.packages("rstan")
devtools::install_github("danmorse314/hockeyR")
